# Generated by Django 5.2a1 on 2025-04-09 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('primary_type', models.CharField(max_length=50)),
                ('secondary_type', models.CharField(max_length=50)),
                ('sprite', models.CharField(max_length=200)),
                ('pkdex', models.CharField(max_length=400)),
                ('rarity', models.IntegerField()),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
