# Generated by Django 5.2 on 2025-04-10 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Collection', '0002_alter_pokemon_owner'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to='marketplace.marketpost')),
                ('pokemon_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_offered', to='Collection.pokemon')),
                ('pokemon_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_requested', to='Collection.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
