# Generated by Django 5.2 on 2025-04-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0002_alter_pokemon_owner'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='pokemon_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_offers_requested', to='Collection.pokemon'),
        ),
    ]
