# Generated by Django 5.2 on 2025-04-27 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0002_alter_pokemon_owner'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpost',
            name='gold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketpost',
            name='requested_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pokemon_set', to='Collection.pokemon'),
        ),
        migrations.AlterField(
            model_name='marketpost',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_pokemon_set', to='Collection.pokemon'),
        ),
    ]
